require: rubocop-rails
Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'vendor/**/*'

Metrics/AbcSize:
  Max: 20
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - db/seeds.rb
    - spec/**/*
Metrics/ClassLength:
  Max: 150
Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
