plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config.ru'
    - 'config/{environments,initializers}/*'
    - 'config/{application,boot,ci,environment,puma,spring}.rb'
    - 'db/migrate/*'
    - 'db/cable_schema.rb'
    - 'db/schema.rb'
    - 'vendor/**/*'
  NewCops: enable

Capybara/ClickLinkOrButtonStyle:
  Enabled: false

Metrics/AbcSize:
  Max: 20
Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - db/seeds.rb
    - spec/**/*
Metrics/ClassLength:
  Max: 150
Metrics/MethodLength:
  Max: 20

RSpec/DescribeClass:
  Exclude:
    - spec/tasks/**/*
    - spec/system/**/*

Style/Documentation:
  Enabled: false
