require: rubocop-rails
Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'vendor/**/*'

# Can't see any reason why this is better.
Rails/ReadWriteAttribute:
  Enabled: false

# `.describe` blocks are often pretty long,
# but I think that's fine
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

# Relax complexity testing to codeclimate standards (roughly).
Metrics/AbcSize:
  Max: 20
Metrics/MethodLength:
  Max: 20
Metrics/ClassLength:
  Max: 150

# Don't worry about documentation for now.
# In particular, this fails for things like
# controller files, which seems unnecessary.
Style/Documentation:
  Enabled: false

Style/GuardClause:
  MinBodyLength: 10

# I think multiline block chains are beautiful.
Style/MultilineBlockChain:
  Enabled: false

# I think this cop disagrees with nested calls
# which are perfectly clear.
Style/NestedParenthesizedCalls:
  Enabled: false

# I like my method names.
Naming/PredicateName:
  Enabled: false
