require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/**/*'
    - 'config.ru'
    - 'config/**/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
  NewCops: enable

Metrics/AbcSize:
  Max: 20
Metrics/BlockLength:
  Exclude:
    - db/seeds.rb
    - spec/**/*
Metrics/ClassLength:
  Max: 150
Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false
